/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kristianlm_robotanks_box2dbridge_jnibox2d_JNIBox2DShape */

#ifndef _Included_com_kristianlm_robotanks_box2dbridge_jnibox2d_JNIBox2DShape
#define _Included_com_kristianlm_robotanks_box2dbridge_jnibox2d_JNIBox2DShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kristianlm_robotanks_box2dbridge_jnibox2d_JNIBox2DShape
 * Method:    nAssociateShape
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_kristianlm_robotanks_box2dbridge_jnibox2d_JNIBox2DShape_nAssociateShape
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
